// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CorsClient is the client API for Cors service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CorsClient interface {
	Preflight(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type corsClient struct {
	cc grpc.ClientConnInterface
}

func NewCorsClient(cc grpc.ClientConnInterface) CorsClient {
	return &corsClient{cc}
}

func (c *corsClient) Preflight(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/heyrenee.v1.Cors/Preflight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CorsServer is the server API for Cors service.
// All implementations must embed UnimplementedCorsServer
// for forward compatibility
type CorsServer interface {
	Preflight(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedCorsServer()
}

// UnimplementedCorsServer must be embedded to have forward compatible implementations.
type UnimplementedCorsServer struct {
}

func (UnimplementedCorsServer) Preflight(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Preflight not implemented")
}
func (UnimplementedCorsServer) mustEmbedUnimplementedCorsServer() {}

// UnsafeCorsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CorsServer will
// result in compilation errors.
type UnsafeCorsServer interface {
	mustEmbedUnimplementedCorsServer()
}

func RegisterCorsServer(s grpc.ServiceRegistrar, srv CorsServer) {
	s.RegisterService(&Cors_ServiceDesc, srv)
}

func _Cors_Preflight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorsServer).Preflight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/heyrenee.v1.Cors/Preflight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorsServer).Preflight(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Cors_ServiceDesc is the grpc.ServiceDesc for Cors service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cors_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "heyrenee.v1.Cors",
	HandlerType: (*CorsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Preflight",
			Handler:    _Cors_Preflight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "heyrenee/v1/cors.proto",
}
