// source: heyrenee/v1/insurance_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var heyrenee_v1_messages_insurance_pb = require('../../heyrenee/v1/messages/insurance_pb.js');
goog.object.extend(proto, heyrenee_v1_messages_insurance_pb);
var heyrenee_v1_options_auth_pb = require('../../heyrenee/v1/options/auth_pb.js');
goog.object.extend(proto, heyrenee_v1_options_auth_pb);
goog.exportSymbol('proto.heyrenee.v1.CreateInsuranceRequest', null, global);
goog.exportSymbol('proto.heyrenee.v1.ListInsuranceRequest', null, global);
goog.exportSymbol('proto.heyrenee.v1.ListInsuranceResponse', null, global);
goog.exportSymbol('proto.heyrenee.v1.UpdateInsuranceRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.heyrenee.v1.CreateInsuranceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.heyrenee.v1.CreateInsuranceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.heyrenee.v1.CreateInsuranceRequest.displayName = 'proto.heyrenee.v1.CreateInsuranceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.heyrenee.v1.UpdateInsuranceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.heyrenee.v1.UpdateInsuranceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.heyrenee.v1.UpdateInsuranceRequest.displayName = 'proto.heyrenee.v1.UpdateInsuranceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.heyrenee.v1.ListInsuranceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.heyrenee.v1.ListInsuranceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.heyrenee.v1.ListInsuranceRequest.displayName = 'proto.heyrenee.v1.ListInsuranceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.heyrenee.v1.ListInsuranceResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.heyrenee.v1.ListInsuranceResponse.repeatedFields_, null);
};
goog.inherits(proto.heyrenee.v1.ListInsuranceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.heyrenee.v1.ListInsuranceResponse.displayName = 'proto.heyrenee.v1.ListInsuranceResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.heyrenee.v1.CreateInsuranceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.heyrenee.v1.CreateInsuranceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.heyrenee.v1.CreateInsuranceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.CreateInsuranceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    insurance: (f = msg.getInsurance()) && heyrenee_v1_messages_insurance_pb.Insurance.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.heyrenee.v1.CreateInsuranceRequest}
 */
proto.heyrenee.v1.CreateInsuranceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.heyrenee.v1.CreateInsuranceRequest;
  return proto.heyrenee.v1.CreateInsuranceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.heyrenee.v1.CreateInsuranceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.heyrenee.v1.CreateInsuranceRequest}
 */
proto.heyrenee.v1.CreateInsuranceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new heyrenee_v1_messages_insurance_pb.Insurance;
      reader.readMessage(value,heyrenee_v1_messages_insurance_pb.Insurance.deserializeBinaryFromReader);
      msg.setInsurance(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.heyrenee.v1.CreateInsuranceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.heyrenee.v1.CreateInsuranceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.heyrenee.v1.CreateInsuranceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.CreateInsuranceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInsurance();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      heyrenee_v1_messages_insurance_pb.Insurance.serializeBinaryToWriter
    );
  }
};


/**
 * optional messages.Insurance insurance = 1;
 * @return {?proto.heyrenee.v1.messages.Insurance}
 */
proto.heyrenee.v1.CreateInsuranceRequest.prototype.getInsurance = function() {
  return /** @type{?proto.heyrenee.v1.messages.Insurance} */ (
    jspb.Message.getWrapperField(this, heyrenee_v1_messages_insurance_pb.Insurance, 1));
};


/**
 * @param {?proto.heyrenee.v1.messages.Insurance|undefined} value
 * @return {!proto.heyrenee.v1.CreateInsuranceRequest} returns this
*/
proto.heyrenee.v1.CreateInsuranceRequest.prototype.setInsurance = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.heyrenee.v1.CreateInsuranceRequest} returns this
 */
proto.heyrenee.v1.CreateInsuranceRequest.prototype.clearInsurance = function() {
  return this.setInsurance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.CreateInsuranceRequest.prototype.hasInsurance = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.heyrenee.v1.UpdateInsuranceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.heyrenee.v1.UpdateInsuranceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.heyrenee.v1.UpdateInsuranceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.UpdateInsuranceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    insurance: (f = msg.getInsurance()) && heyrenee_v1_messages_insurance_pb.Insurance.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.heyrenee.v1.UpdateInsuranceRequest}
 */
proto.heyrenee.v1.UpdateInsuranceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.heyrenee.v1.UpdateInsuranceRequest;
  return proto.heyrenee.v1.UpdateInsuranceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.heyrenee.v1.UpdateInsuranceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.heyrenee.v1.UpdateInsuranceRequest}
 */
proto.heyrenee.v1.UpdateInsuranceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new heyrenee_v1_messages_insurance_pb.Insurance;
      reader.readMessage(value,heyrenee_v1_messages_insurance_pb.Insurance.deserializeBinaryFromReader);
      msg.setInsurance(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.heyrenee.v1.UpdateInsuranceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.heyrenee.v1.UpdateInsuranceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.heyrenee.v1.UpdateInsuranceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.UpdateInsuranceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInsurance();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      heyrenee_v1_messages_insurance_pb.Insurance.serializeBinaryToWriter
    );
  }
};


/**
 * optional messages.Insurance insurance = 1;
 * @return {?proto.heyrenee.v1.messages.Insurance}
 */
proto.heyrenee.v1.UpdateInsuranceRequest.prototype.getInsurance = function() {
  return /** @type{?proto.heyrenee.v1.messages.Insurance} */ (
    jspb.Message.getWrapperField(this, heyrenee_v1_messages_insurance_pb.Insurance, 1));
};


/**
 * @param {?proto.heyrenee.v1.messages.Insurance|undefined} value
 * @return {!proto.heyrenee.v1.UpdateInsuranceRequest} returns this
*/
proto.heyrenee.v1.UpdateInsuranceRequest.prototype.setInsurance = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.heyrenee.v1.UpdateInsuranceRequest} returns this
 */
proto.heyrenee.v1.UpdateInsuranceRequest.prototype.clearInsurance = function() {
  return this.setInsurance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.UpdateInsuranceRequest.prototype.hasInsurance = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.heyrenee.v1.ListInsuranceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.heyrenee.v1.ListInsuranceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.heyrenee.v1.ListInsuranceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.ListInsuranceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    patientId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    insuranceStatus: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.heyrenee.v1.ListInsuranceRequest}
 */
proto.heyrenee.v1.ListInsuranceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.heyrenee.v1.ListInsuranceRequest;
  return proto.heyrenee.v1.ListInsuranceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.heyrenee.v1.ListInsuranceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.heyrenee.v1.ListInsuranceRequest}
 */
proto.heyrenee.v1.ListInsuranceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPatientId(value);
      break;
    case 2:
      var value = /** @type {!proto.heyrenee.v1.messages.InsuranceStatus} */ (reader.readEnum());
      msg.setInsuranceStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.heyrenee.v1.ListInsuranceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.heyrenee.v1.ListInsuranceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.heyrenee.v1.ListInsuranceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.ListInsuranceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPatientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInsuranceStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional string patient_id = 1;
 * @return {string}
 */
proto.heyrenee.v1.ListInsuranceRequest.prototype.getPatientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.ListInsuranceRequest} returns this
 */
proto.heyrenee.v1.ListInsuranceRequest.prototype.setPatientId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional messages.InsuranceStatus insurance_status = 2;
 * @return {!proto.heyrenee.v1.messages.InsuranceStatus}
 */
proto.heyrenee.v1.ListInsuranceRequest.prototype.getInsuranceStatus = function() {
  return /** @type {!proto.heyrenee.v1.messages.InsuranceStatus} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.heyrenee.v1.messages.InsuranceStatus} value
 * @return {!proto.heyrenee.v1.ListInsuranceRequest} returns this
 */
proto.heyrenee.v1.ListInsuranceRequest.prototype.setInsuranceStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.heyrenee.v1.ListInsuranceResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.heyrenee.v1.ListInsuranceResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.heyrenee.v1.ListInsuranceResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.heyrenee.v1.ListInsuranceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.ListInsuranceResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    insuranceList: jspb.Message.toObjectList(msg.getInsuranceList(),
    heyrenee_v1_messages_insurance_pb.Insurance.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.heyrenee.v1.ListInsuranceResponse}
 */
proto.heyrenee.v1.ListInsuranceResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.heyrenee.v1.ListInsuranceResponse;
  return proto.heyrenee.v1.ListInsuranceResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.heyrenee.v1.ListInsuranceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.heyrenee.v1.ListInsuranceResponse}
 */
proto.heyrenee.v1.ListInsuranceResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new heyrenee_v1_messages_insurance_pb.Insurance;
      reader.readMessage(value,heyrenee_v1_messages_insurance_pb.Insurance.deserializeBinaryFromReader);
      msg.addInsurance(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.heyrenee.v1.ListInsuranceResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.heyrenee.v1.ListInsuranceResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.heyrenee.v1.ListInsuranceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.ListInsuranceResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInsuranceList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      heyrenee_v1_messages_insurance_pb.Insurance.serializeBinaryToWriter
    );
  }
};


/**
 * repeated messages.Insurance insurance = 1;
 * @return {!Array<!proto.heyrenee.v1.messages.Insurance>}
 */
proto.heyrenee.v1.ListInsuranceResponse.prototype.getInsuranceList = function() {
  return /** @type{!Array<!proto.heyrenee.v1.messages.Insurance>} */ (
    jspb.Message.getRepeatedWrapperField(this, heyrenee_v1_messages_insurance_pb.Insurance, 1));
};


/**
 * @param {!Array<!proto.heyrenee.v1.messages.Insurance>} value
 * @return {!proto.heyrenee.v1.ListInsuranceResponse} returns this
*/
proto.heyrenee.v1.ListInsuranceResponse.prototype.setInsuranceList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.heyrenee.v1.messages.Insurance=} opt_value
 * @param {number=} opt_index
 * @return {!proto.heyrenee.v1.messages.Insurance}
 */
proto.heyrenee.v1.ListInsuranceResponse.prototype.addInsurance = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.heyrenee.v1.messages.Insurance, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.heyrenee.v1.ListInsuranceResponse} returns this
 */
proto.heyrenee.v1.ListInsuranceResponse.prototype.clearInsuranceList = function() {
  return this.setInsuranceList([]);
};


goog.object.extend(exports, proto.heyrenee.v1);
