// source: heyrenee/v1/messages/insurance.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var heyrenee_v1_options_auth_pb = require('../../../heyrenee/v1/options/auth_pb.js');
goog.object.extend(proto, heyrenee_v1_options_auth_pb);
goog.exportSymbol('proto.heyrenee.v1.messages.Insurance', null, global);
goog.exportSymbol('proto.heyrenee.v1.messages.InsuranceStatus', null, global);
goog.exportSymbol('proto.heyrenee.v1.messages.InsuranceType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.heyrenee.v1.messages.Insurance = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.heyrenee.v1.messages.Insurance.repeatedFields_, null);
};
goog.inherits(proto.heyrenee.v1.messages.Insurance, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.heyrenee.v1.messages.Insurance.displayName = 'proto.heyrenee.v1.messages.Insurance';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.heyrenee.v1.messages.Insurance.repeatedFields_ = [7,15,29];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.heyrenee.v1.messages.Insurance.prototype.toObject = function(opt_includeInstance) {
  return proto.heyrenee.v1.messages.Insurance.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.heyrenee.v1.messages.Insurance} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.messages.Insurance.toObject = function(includeInstance, msg) {
  var f, obj = {
    patientId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    insuranceId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    insurer: jspb.Message.getFieldWithDefault(msg, 3, ""),
    insuranceType: jspb.Message.getFieldWithDefault(msg, 4, 0),
    insuranceStatus: jspb.Message.getFieldWithDefault(msg, 5, 0),
    policyOwnerName: jspb.Message.getFieldWithDefault(msg, 6, ""),
    policyOwnerAddressLinesList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    policyOwnerCity: jspb.Message.getFieldWithDefault(msg, 8, ""),
    policyOwnerState: jspb.Message.getFieldWithDefault(msg, 9, ""),
    policyOwnerZip: jspb.Message.getFieldWithDefault(msg, 10, ""),
    policyOwnerPhone: jspb.Message.getFieldWithDefault(msg, 11, ""),
    groupNumber: jspb.Message.getFieldWithDefault(msg, 12, ""),
    policyNumber: jspb.Message.getFieldWithDefault(msg, 13, ""),
    rxPolicyNumber: jspb.Message.getFieldWithDefault(msg, 14, ""),
    claimsAddressLinesList: (f = jspb.Message.getRepeatedField(msg, 15)) == null ? undefined : f,
    claimsCity: jspb.Message.getFieldWithDefault(msg, 16, ""),
    claimsState: jspb.Message.getFieldWithDefault(msg, 17, ""),
    claimsZip: jspb.Message.getFieldWithDefault(msg, 18, ""),
    claimsPhone: jspb.Message.getFieldWithDefault(msg, 19, ""),
    rxClaimsAddressLinesList: (f = jspb.Message.getRepeatedField(msg, 29)) == null ? undefined : f,
    rxClaimsCity: jspb.Message.getFieldWithDefault(msg, 21, ""),
    rxClaimsState: jspb.Message.getFieldWithDefault(msg, 22, ""),
    rxClaimsZip: jspb.Message.getFieldWithDefault(msg, 23, ""),
    rxClaimsPhone: jspb.Message.getFieldWithDefault(msg, 24, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.heyrenee.v1.messages.Insurance}
 */
proto.heyrenee.v1.messages.Insurance.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.heyrenee.v1.messages.Insurance;
  return proto.heyrenee.v1.messages.Insurance.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.heyrenee.v1.messages.Insurance} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.heyrenee.v1.messages.Insurance}
 */
proto.heyrenee.v1.messages.Insurance.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPatientId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setInsuranceId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setInsurer(value);
      break;
    case 4:
      var value = /** @type {!proto.heyrenee.v1.messages.InsuranceType} */ (reader.readEnum());
      msg.setInsuranceType(value);
      break;
    case 5:
      var value = /** @type {!proto.heyrenee.v1.messages.InsuranceStatus} */ (reader.readEnum());
      msg.setInsuranceStatus(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPolicyOwnerName(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addPolicyOwnerAddressLines(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setPolicyOwnerCity(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setPolicyOwnerState(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setPolicyOwnerZip(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setPolicyOwnerPhone(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setGroupNumber(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setPolicyNumber(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setRxPolicyNumber(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.addClaimsAddressLines(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setClaimsCity(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setClaimsState(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setClaimsZip(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setClaimsPhone(value);
      break;
    case 29:
      var value = /** @type {string} */ (reader.readString());
      msg.addRxClaimsAddressLines(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setRxClaimsCity(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.setRxClaimsState(value);
      break;
    case 23:
      var value = /** @type {string} */ (reader.readString());
      msg.setRxClaimsZip(value);
      break;
    case 24:
      var value = /** @type {string} */ (reader.readString());
      msg.setRxClaimsPhone(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.heyrenee.v1.messages.Insurance.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.heyrenee.v1.messages.Insurance.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.heyrenee.v1.messages.Insurance} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.messages.Insurance.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPatientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInsuranceId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getInsurer();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getInsuranceType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getInsuranceStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getPolicyOwnerName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getPolicyOwnerAddressLinesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getPolicyOwnerCity();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getPolicyOwnerState();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getPolicyOwnerZip();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getPolicyOwnerPhone();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getGroupNumber();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getPolicyNumber();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getRxPolicyNumber();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getClaimsAddressLinesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      15,
      f
    );
  }
  f = message.getClaimsCity();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getClaimsState();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getClaimsZip();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getClaimsPhone();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getRxClaimsAddressLinesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      29,
      f
    );
  }
  f = message.getRxClaimsCity();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getRxClaimsState();
  if (f.length > 0) {
    writer.writeString(
      22,
      f
    );
  }
  f = message.getRxClaimsZip();
  if (f.length > 0) {
    writer.writeString(
      23,
      f
    );
  }
  f = message.getRxClaimsPhone();
  if (f.length > 0) {
    writer.writeString(
      24,
      f
    );
  }
};


/**
 * optional string patient_id = 1;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getPatientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setPatientId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string insurance_id = 2;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getInsuranceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setInsuranceId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string insurer = 3;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getInsurer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setInsurer = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional InsuranceType insurance_type = 4;
 * @return {!proto.heyrenee.v1.messages.InsuranceType}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getInsuranceType = function() {
  return /** @type {!proto.heyrenee.v1.messages.InsuranceType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.heyrenee.v1.messages.InsuranceType} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setInsuranceType = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional InsuranceStatus insurance_status = 5;
 * @return {!proto.heyrenee.v1.messages.InsuranceStatus}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getInsuranceStatus = function() {
  return /** @type {!proto.heyrenee.v1.messages.InsuranceStatus} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.heyrenee.v1.messages.InsuranceStatus} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setInsuranceStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional string policy_owner_name = 6;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getPolicyOwnerName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setPolicyOwnerName = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * repeated string policy_owner_address_lines = 7;
 * @return {!Array<string>}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getPolicyOwnerAddressLinesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setPolicyOwnerAddressLinesList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.addPolicyOwnerAddressLines = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.clearPolicyOwnerAddressLinesList = function() {
  return this.setPolicyOwnerAddressLinesList([]);
};


/**
 * optional string policy_owner_city = 8;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getPolicyOwnerCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setPolicyOwnerCity = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string policy_owner_state = 9;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getPolicyOwnerState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setPolicyOwnerState = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string policy_owner_zip = 10;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getPolicyOwnerZip = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setPolicyOwnerZip = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string policy_owner_phone = 11;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getPolicyOwnerPhone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setPolicyOwnerPhone = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string group_number = 12;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getGroupNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setGroupNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string policy_number = 13;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getPolicyNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setPolicyNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string rx_policy_number = 14;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getRxPolicyNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setRxPolicyNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * repeated string claims_address_lines = 15;
 * @return {!Array<string>}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getClaimsAddressLinesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 15));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setClaimsAddressLinesList = function(value) {
  return jspb.Message.setField(this, 15, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.addClaimsAddressLines = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 15, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.clearClaimsAddressLinesList = function() {
  return this.setClaimsAddressLinesList([]);
};


/**
 * optional string claims_city = 16;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getClaimsCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setClaimsCity = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional string claims_state = 17;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getClaimsState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setClaimsState = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional string claims_zip = 18;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getClaimsZip = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setClaimsZip = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * optional string claims_phone = 19;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getClaimsPhone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setClaimsPhone = function(value) {
  return jspb.Message.setProto3StringField(this, 19, value);
};


/**
 * repeated string rx_claims_address_lines = 29;
 * @return {!Array<string>}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getRxClaimsAddressLinesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 29));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setRxClaimsAddressLinesList = function(value) {
  return jspb.Message.setField(this, 29, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.addRxClaimsAddressLines = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 29, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.clearRxClaimsAddressLinesList = function() {
  return this.setRxClaimsAddressLinesList([]);
};


/**
 * optional string rx_claims_city = 21;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getRxClaimsCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setRxClaimsCity = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * optional string rx_claims_state = 22;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getRxClaimsState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setRxClaimsState = function(value) {
  return jspb.Message.setProto3StringField(this, 22, value);
};


/**
 * optional string rx_claims_zip = 23;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getRxClaimsZip = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 23, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setRxClaimsZip = function(value) {
  return jspb.Message.setProto3StringField(this, 23, value);
};


/**
 * optional string rx_claims_phone = 24;
 * @return {string}
 */
proto.heyrenee.v1.messages.Insurance.prototype.getRxClaimsPhone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 24, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Insurance} returns this
 */
proto.heyrenee.v1.messages.Insurance.prototype.setRxClaimsPhone = function(value) {
  return jspb.Message.setProto3StringField(this, 24, value);
};


/**
 * @enum {number}
 */
proto.heyrenee.v1.messages.InsuranceType = {
  INSURANCE_TYPE_UNSPECIFIED: 0,
  INSURANCE_TYPE_MEDICAID: 1,
  INSURANCE_TYPE_MEDICARE: 2,
  INSURANCE_TYPE_MEDICARE_ADVANTAGE: 3,
  INSURANCE_TYPE_VETERANS_AFFAIRS: 4,
  INSURANCE_TYPE_EMPLOYER_BASED: 5,
  INSURANCE_TYPE_PRIVATE: 6
};

/**
 * @enum {number}
 */
proto.heyrenee.v1.messages.InsuranceStatus = {
  INSURANCE_STATUS_UNSPECIFIED: 0,
  INSURANCE_STATUS_ACTIVE: 1,
  INSURANCE_STATUS_INACTIVE: 2
};

goog.object.extend(exports, proto.heyrenee.v1.messages);
