// source: heyrenee/v1/messages/patient_satisfaction_questionnaire.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var heyrenee_v1_options_auth_pb = require('../../../heyrenee/v1/options/auth_pb.js');
goog.object.extend(proto, heyrenee_v1_options_auth_pb);
var heyrenee_v1_enums_language_pb = require('../../../heyrenee/v1/enums/language_pb.js');
goog.object.extend(proto, heyrenee_v1_enums_language_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.displayName = 'proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.toObject = function(opt_includeInstance) {
  return proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.toObject = function(includeInstance, msg) {
  var f, obj = {
    patientId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    patientSatisfactionQuestionnaireId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    questionnaireLanguage: jspb.Message.getFieldWithDefault(msg, 3, 0),
    dateTimeAnswered: (f = msg.getDateTimeAnswered()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    healthStatus: jspb.Message.getFieldWithDefault(msg, 5, 0),
    medicalCareSatisfaction: jspb.Message.getFieldWithDefault(msg, 6, 0),
    healthSatisfaction: jspb.Message.getFieldWithDefault(msg, 7, 0),
    heyReneeSatisfaction: jspb.Message.getFieldWithDefault(msg, 8, 0),
    primaryCareProviderSatisfaction: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire}
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire;
  return proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire}
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPatientId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPatientSatisfactionQuestionnaireId(value);
      break;
    case 3:
      var value = /** @type {!proto.heyrenee.v1.enums.Language} */ (reader.readEnum());
      msg.setQuestionnaireLanguage(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDateTimeAnswered(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setHealthStatus(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMedicalCareSatisfaction(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setHealthSatisfaction(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setHeyReneeSatisfaction(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPrimaryCareProviderSatisfaction(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPatientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPatientSatisfactionQuestionnaireId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getQuestionnaireLanguage();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getDateTimeAnswered();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getHealthStatus();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getMedicalCareSatisfaction();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getHealthSatisfaction();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getHeyReneeSatisfaction();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getPrimaryCareProviderSatisfaction();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
};


/**
 * optional string patient_id = 1;
 * @return {string}
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.getPatientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire} returns this
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.setPatientId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string patient_satisfaction_questionnaire_id = 2;
 * @return {string}
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.getPatientSatisfactionQuestionnaireId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire} returns this
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.setPatientSatisfactionQuestionnaireId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional heyrenee.v1.enums.Language questionnaire_language = 3;
 * @return {!proto.heyrenee.v1.enums.Language}
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.getQuestionnaireLanguage = function() {
  return /** @type {!proto.heyrenee.v1.enums.Language} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.heyrenee.v1.enums.Language} value
 * @return {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire} returns this
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.setQuestionnaireLanguage = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp date_time_answered = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.getDateTimeAnswered = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire} returns this
*/
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.setDateTimeAnswered = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire} returns this
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.clearDateTimeAnswered = function() {
  return this.setDateTimeAnswered(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.hasDateTimeAnswered = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int64 health_status = 5;
 * @return {number}
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.getHealthStatus = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire} returns this
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.setHealthStatus = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 medical_care_satisfaction = 6;
 * @return {number}
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.getMedicalCareSatisfaction = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire} returns this
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.setMedicalCareSatisfaction = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int64 health_satisfaction = 7;
 * @return {number}
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.getHealthSatisfaction = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire} returns this
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.setHealthSatisfaction = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 hey_renee_satisfaction = 8;
 * @return {number}
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.getHeyReneeSatisfaction = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire} returns this
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.setHeyReneeSatisfaction = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int64 primary_care_provider_satisfaction = 9;
 * @return {number}
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.getPrimaryCareProviderSatisfaction = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire} returns this
 */
proto.heyrenee.v1.messages.PatientSatisfactionQuestionnaire.prototype.setPrimaryCareProviderSatisfaction = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


goog.object.extend(exports, proto.heyrenee.v1.messages);
