// source: heyrenee/v1/messages/patient_caregiver.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var heyrenee_v1_messages_caregiver_pb = require('../../../heyrenee/v1/messages/caregiver_pb.js');
goog.object.extend(proto, heyrenee_v1_messages_caregiver_pb);
var heyrenee_v1_options_auth_pb = require('../../../heyrenee/v1/options/auth_pb.js');
goog.object.extend(proto, heyrenee_v1_options_auth_pb);
goog.exportSymbol('proto.heyrenee.v1.messages.PatientCaregiver', null, global);
goog.exportSymbol('proto.heyrenee.v1.messages.PatientCaregiver.CaregiverCase', null, global);
goog.exportSymbol('proto.heyrenee.v1.messages.PatientCaregiverAccess', null, global);
goog.exportSymbol('proto.heyrenee.v1.messages.PatientCaregiverRelationship', null, global);
goog.exportSymbol('proto.heyrenee.v1.messages.PatientCaregiverType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.heyrenee.v1.messages.PatientCaregiver = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.heyrenee.v1.messages.PatientCaregiver.oneofGroups_);
};
goog.inherits(proto.heyrenee.v1.messages.PatientCaregiver, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.heyrenee.v1.messages.PatientCaregiver.displayName = 'proto.heyrenee.v1.messages.PatientCaregiver';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.heyrenee.v1.messages.PatientCaregiver.oneofGroups_ = [[2,3]];

/**
 * @enum {number}
 */
proto.heyrenee.v1.messages.PatientCaregiver.CaregiverCase = {
  CAREGIVER_NOT_SET: 0,
  CAREGIVER_ID: 2,
  CAREGIVER_MESSAGE: 3
};

/**
 * @return {proto.heyrenee.v1.messages.PatientCaregiver.CaregiverCase}
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.getCaregiverCase = function() {
  return /** @type {proto.heyrenee.v1.messages.PatientCaregiver.CaregiverCase} */(jspb.Message.computeOneofCase(this, proto.heyrenee.v1.messages.PatientCaregiver.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.toObject = function(opt_includeInstance) {
  return proto.heyrenee.v1.messages.PatientCaregiver.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.heyrenee.v1.messages.PatientCaregiver} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.messages.PatientCaregiver.toObject = function(includeInstance, msg) {
  var f, obj = {
    patientId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    caregiverId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    caregiverMessage: (f = msg.getCaregiverMessage()) && heyrenee_v1_messages_caregiver_pb.Caregiver.toObject(includeInstance, f),
    preferredName: jspb.Message.getFieldWithDefault(msg, 4, ""),
    patientCaregiverType: jspb.Message.getFieldWithDefault(msg, 5, 0),
    patientCaregiverAccess: jspb.Message.getFieldWithDefault(msg, 6, 0),
    patientCaregiverRelationship: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.heyrenee.v1.messages.PatientCaregiver}
 */
proto.heyrenee.v1.messages.PatientCaregiver.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.heyrenee.v1.messages.PatientCaregiver;
  return proto.heyrenee.v1.messages.PatientCaregiver.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.heyrenee.v1.messages.PatientCaregiver} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.heyrenee.v1.messages.PatientCaregiver}
 */
proto.heyrenee.v1.messages.PatientCaregiver.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPatientId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCaregiverId(value);
      break;
    case 3:
      var value = new heyrenee_v1_messages_caregiver_pb.Caregiver;
      reader.readMessage(value,heyrenee_v1_messages_caregiver_pb.Caregiver.deserializeBinaryFromReader);
      msg.setCaregiverMessage(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPreferredName(value);
      break;
    case 5:
      var value = /** @type {!proto.heyrenee.v1.messages.PatientCaregiverType} */ (reader.readEnum());
      msg.setPatientCaregiverType(value);
      break;
    case 6:
      var value = /** @type {!proto.heyrenee.v1.messages.PatientCaregiverAccess} */ (reader.readEnum());
      msg.setPatientCaregiverAccess(value);
      break;
    case 7:
      var value = /** @type {!proto.heyrenee.v1.messages.PatientCaregiverRelationship} */ (reader.readEnum());
      msg.setPatientCaregiverRelationship(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.heyrenee.v1.messages.PatientCaregiver.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.heyrenee.v1.messages.PatientCaregiver} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.messages.PatientCaregiver.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPatientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCaregiverMessage();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      heyrenee_v1_messages_caregiver_pb.Caregiver.serializeBinaryToWriter
    );
  }
  f = message.getPreferredName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPatientCaregiverType();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = message.getPatientCaregiverAccess();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getPatientCaregiverRelationship();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
};


/**
 * optional string patient_id = 1;
 * @return {string}
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.getPatientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.PatientCaregiver} returns this
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.setPatientId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string caregiver_id = 2;
 * @return {string}
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.getCaregiverId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.PatientCaregiver} returns this
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.setCaregiverId = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.heyrenee.v1.messages.PatientCaregiver.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.heyrenee.v1.messages.PatientCaregiver} returns this
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.clearCaregiverId = function() {
  return jspb.Message.setOneofField(this, 2, proto.heyrenee.v1.messages.PatientCaregiver.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.hasCaregiverId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Caregiver caregiver_message = 3;
 * @return {?proto.heyrenee.v1.messages.Caregiver}
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.getCaregiverMessage = function() {
  return /** @type{?proto.heyrenee.v1.messages.Caregiver} */ (
    jspb.Message.getWrapperField(this, heyrenee_v1_messages_caregiver_pb.Caregiver, 3));
};


/**
 * @param {?proto.heyrenee.v1.messages.Caregiver|undefined} value
 * @return {!proto.heyrenee.v1.messages.PatientCaregiver} returns this
*/
proto.heyrenee.v1.messages.PatientCaregiver.prototype.setCaregiverMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.heyrenee.v1.messages.PatientCaregiver.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.heyrenee.v1.messages.PatientCaregiver} returns this
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.clearCaregiverMessage = function() {
  return this.setCaregiverMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.hasCaregiverMessage = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string preferred_name = 4;
 * @return {string}
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.getPreferredName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.PatientCaregiver} returns this
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.setPreferredName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional PatientCaregiverType patient_caregiver_type = 5;
 * @return {!proto.heyrenee.v1.messages.PatientCaregiverType}
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.getPatientCaregiverType = function() {
  return /** @type {!proto.heyrenee.v1.messages.PatientCaregiverType} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.heyrenee.v1.messages.PatientCaregiverType} value
 * @return {!proto.heyrenee.v1.messages.PatientCaregiver} returns this
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.setPatientCaregiverType = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional PatientCaregiverAccess patient_caregiver_access = 6;
 * @return {!proto.heyrenee.v1.messages.PatientCaregiverAccess}
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.getPatientCaregiverAccess = function() {
  return /** @type {!proto.heyrenee.v1.messages.PatientCaregiverAccess} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.heyrenee.v1.messages.PatientCaregiverAccess} value
 * @return {!proto.heyrenee.v1.messages.PatientCaregiver} returns this
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.setPatientCaregiverAccess = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional PatientCaregiverRelationship patient_caregiver_relationship = 7;
 * @return {!proto.heyrenee.v1.messages.PatientCaregiverRelationship}
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.getPatientCaregiverRelationship = function() {
  return /** @type {!proto.heyrenee.v1.messages.PatientCaregiverRelationship} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.heyrenee.v1.messages.PatientCaregiverRelationship} value
 * @return {!proto.heyrenee.v1.messages.PatientCaregiver} returns this
 */
proto.heyrenee.v1.messages.PatientCaregiver.prototype.setPatientCaregiverRelationship = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * @enum {number}
 */
proto.heyrenee.v1.messages.PatientCaregiverType = {
  PATIENT_CAREGIVER_TYPE_UNSPECIFIED: 0,
  PATIENT_CAREGIVER_TYPE_PRIMARY: 1
};

/**
 * @enum {number}
 */
proto.heyrenee.v1.messages.PatientCaregiverAccess = {
  PATIENT_CAREGIVER_ACCESS_UNSPECIFIED: 0,
  PATIENT_CAREGIVER_ACCESS_NONE: 1,
  PATIENT_CAREGIVER_ACCESS_DASHBOARD: 2
};

/**
 * @enum {number}
 */
proto.heyrenee.v1.messages.PatientCaregiverRelationship = {
  PATIENT_CAREGIVER_RELATIONSHIP_UNSPECIFIED: 0,
  PATIENT_CAREGIVER_RELATIONSHIP_CHILD: 1,
  PATIENT_CAREGIVER_RELATIONSHIP_PARENT: 2,
  PATIENT_CAREGIVER_RELATIONSHIP_GRANDPARENT: 3,
  PATIENT_CAREGIVER_RELATIONSHIP_GRANDCHILD: 4,
  PATIENT_CAREGIVER_RELATIONSHIP_EXTENDED_FAMILY: 5,
  PATIENT_CAREGIVER_RELATIONSHIP_FRIEND: 6,
  PATIENT_CAREGIVER_RELATIONSHIP_HEALTH_AIDE: 7,
  PATIENT_CAREGIVER_RELATIONSHIP_OTHER: 8
};

goog.object.extend(exports, proto.heyrenee.v1.messages);
