// source: heyrenee/v1/messages/prescription.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var heyrenee_v1_messages_medication_pb = require('../../../heyrenee/v1/messages/medication_pb.js');
goog.object.extend(proto, heyrenee_v1_messages_medication_pb);
var heyrenee_v1_messages_provider_pb = require('../../../heyrenee/v1/messages/provider_pb.js');
goog.object.extend(proto, heyrenee_v1_messages_provider_pb);
var heyrenee_v1_options_auth_pb = require('../../../heyrenee/v1/options/auth_pb.js');
goog.object.extend(proto, heyrenee_v1_options_auth_pb);
goog.exportSymbol('proto.heyrenee.v1.messages.Prescription', null, global);
goog.exportSymbol('proto.heyrenee.v1.messages.Prescription.MedicationCase', null, global);
goog.exportSymbol('proto.heyrenee.v1.messages.Prescription.ProviderCase', null, global);
goog.exportSymbol('proto.heyrenee.v1.messages.PrescriptionStatus', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.heyrenee.v1.messages.Prescription = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.heyrenee.v1.messages.Prescription.repeatedFields_, proto.heyrenee.v1.messages.Prescription.oneofGroups_);
};
goog.inherits(proto.heyrenee.v1.messages.Prescription, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.heyrenee.v1.messages.Prescription.displayName = 'proto.heyrenee.v1.messages.Prescription';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.heyrenee.v1.messages.Prescription.repeatedFields_ = [15];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.heyrenee.v1.messages.Prescription.oneofGroups_ = [[2,3],[5,6]];

/**
 * @enum {number}
 */
proto.heyrenee.v1.messages.Prescription.MedicationCase = {
  MEDICATION_NOT_SET: 0,
  MEDICATION_ID: 2,
  MEDICATION_MESSAGE: 3
};

/**
 * @return {proto.heyrenee.v1.messages.Prescription.MedicationCase}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getMedicationCase = function() {
  return /** @type {proto.heyrenee.v1.messages.Prescription.MedicationCase} */(jspb.Message.computeOneofCase(this, proto.heyrenee.v1.messages.Prescription.oneofGroups_[0]));
};

/**
 * @enum {number}
 */
proto.heyrenee.v1.messages.Prescription.ProviderCase = {
  PROVIDER_NOT_SET: 0,
  PROVIDER_ID: 5,
  PROVIDER_MESSAGE: 6
};

/**
 * @return {proto.heyrenee.v1.messages.Prescription.ProviderCase}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getProviderCase = function() {
  return /** @type {proto.heyrenee.v1.messages.Prescription.ProviderCase} */(jspb.Message.computeOneofCase(this, proto.heyrenee.v1.messages.Prescription.oneofGroups_[1]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.heyrenee.v1.messages.Prescription.prototype.toObject = function(opt_includeInstance) {
  return proto.heyrenee.v1.messages.Prescription.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.heyrenee.v1.messages.Prescription} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.messages.Prescription.toObject = function(includeInstance, msg) {
  var f, obj = {
    patientId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    medicationId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    medicationMessage: (f = msg.getMedicationMessage()) && heyrenee_v1_messages_medication_pb.Medication.toObject(includeInstance, f),
    prescriptionId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    providerId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    providerMessage: (f = msg.getProviderMessage()) && heyrenee_v1_messages_provider_pb.Provider.toObject(includeInstance, f),
    providerInstructions: jspb.Message.getFieldWithDefault(msg, 7, ""),
    patientInstructions: jspb.Message.getFieldWithDefault(msg, 8, ""),
    refillCount: jspb.Message.getFieldWithDefault(msg, 9, 0),
    refillFrequency: (f = msg.getRefillFrequency()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    prescriptionStatus: jspb.Message.getFieldWithDefault(msg, 11, 0),
    firstMedicationRegimenStart: (f = msg.getFirstMedicationRegimenStart()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    medicationRegimenDuration: (f = msg.getMedicationRegimenDuration()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    medicationDosesPerRegimen: jspb.Message.getFieldWithDefault(msg, 14, 0),
    medicationDoseDurationsFromRegimenStartList: jspb.Message.toObjectList(msg.getMedicationDoseDurationsFromRegimenStartList(),
    google_protobuf_duration_pb.Duration.toObject, includeInstance),
    dateWritten: (f = msg.getDateWritten()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.heyrenee.v1.messages.Prescription}
 */
proto.heyrenee.v1.messages.Prescription.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.heyrenee.v1.messages.Prescription;
  return proto.heyrenee.v1.messages.Prescription.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.heyrenee.v1.messages.Prescription} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.heyrenee.v1.messages.Prescription}
 */
proto.heyrenee.v1.messages.Prescription.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPatientId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMedicationId(value);
      break;
    case 3:
      var value = new heyrenee_v1_messages_medication_pb.Medication;
      reader.readMessage(value,heyrenee_v1_messages_medication_pb.Medication.deserializeBinaryFromReader);
      msg.setMedicationMessage(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrescriptionId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setProviderId(value);
      break;
    case 6:
      var value = new heyrenee_v1_messages_provider_pb.Provider;
      reader.readMessage(value,heyrenee_v1_messages_provider_pb.Provider.deserializeBinaryFromReader);
      msg.setProviderMessage(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setProviderInstructions(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setPatientInstructions(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRefillCount(value);
      break;
    case 10:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setRefillFrequency(value);
      break;
    case 11:
      var value = /** @type {!proto.heyrenee.v1.messages.PrescriptionStatus} */ (reader.readEnum());
      msg.setPrescriptionStatus(value);
      break;
    case 12:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setFirstMedicationRegimenStart(value);
      break;
    case 13:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setMedicationRegimenDuration(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMedicationDosesPerRegimen(value);
      break;
    case 15:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.addMedicationDoseDurationsFromRegimenStart(value);
      break;
    case 16:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDateWritten(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.heyrenee.v1.messages.Prescription.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.heyrenee.v1.messages.Prescription.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.heyrenee.v1.messages.Prescription} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.messages.Prescription.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPatientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMedicationMessage();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      heyrenee_v1_messages_medication_pb.Medication.serializeBinaryToWriter
    );
  }
  f = message.getPrescriptionId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getProviderMessage();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      heyrenee_v1_messages_provider_pb.Provider.serializeBinaryToWriter
    );
  }
  f = message.getProviderInstructions();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getPatientInstructions();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getRefillCount();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getRefillFrequency();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getPrescriptionStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      11,
      f
    );
  }
  f = message.getFirstMedicationRegimenStart();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getMedicationRegimenDuration();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getMedicationDosesPerRegimen();
  if (f !== 0) {
    writer.writeInt64(
      14,
      f
    );
  }
  f = message.getMedicationDoseDurationsFromRegimenStartList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      15,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getDateWritten();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string patient_id = 1;
 * @return {string}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getPatientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.setPatientId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string medication_id = 2;
 * @return {string}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getMedicationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.setMedicationId = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.heyrenee.v1.messages.Prescription.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.clearMedicationId = function() {
  return jspb.Message.setOneofField(this, 2, proto.heyrenee.v1.messages.Prescription.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.Prescription.prototype.hasMedicationId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Medication medication_message = 3;
 * @return {?proto.heyrenee.v1.messages.Medication}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getMedicationMessage = function() {
  return /** @type{?proto.heyrenee.v1.messages.Medication} */ (
    jspb.Message.getWrapperField(this, heyrenee_v1_messages_medication_pb.Medication, 3));
};


/**
 * @param {?proto.heyrenee.v1.messages.Medication|undefined} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
*/
proto.heyrenee.v1.messages.Prescription.prototype.setMedicationMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.heyrenee.v1.messages.Prescription.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.clearMedicationMessage = function() {
  return this.setMedicationMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.Prescription.prototype.hasMedicationMessage = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string prescription_id = 4;
 * @return {string}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getPrescriptionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.setPrescriptionId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string provider_id = 5;
 * @return {string}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getProviderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.setProviderId = function(value) {
  return jspb.Message.setOneofField(this, 5, proto.heyrenee.v1.messages.Prescription.oneofGroups_[1], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.clearProviderId = function() {
  return jspb.Message.setOneofField(this, 5, proto.heyrenee.v1.messages.Prescription.oneofGroups_[1], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.Prescription.prototype.hasProviderId = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional Provider provider_message = 6;
 * @return {?proto.heyrenee.v1.messages.Provider}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getProviderMessage = function() {
  return /** @type{?proto.heyrenee.v1.messages.Provider} */ (
    jspb.Message.getWrapperField(this, heyrenee_v1_messages_provider_pb.Provider, 6));
};


/**
 * @param {?proto.heyrenee.v1.messages.Provider|undefined} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
*/
proto.heyrenee.v1.messages.Prescription.prototype.setProviderMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.heyrenee.v1.messages.Prescription.oneofGroups_[1], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.clearProviderMessage = function() {
  return this.setProviderMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.Prescription.prototype.hasProviderMessage = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string provider_instructions = 7;
 * @return {string}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getProviderInstructions = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.setProviderInstructions = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string patient_instructions = 8;
 * @return {string}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getPatientInstructions = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.setPatientInstructions = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional int64 refill_count = 9;
 * @return {number}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getRefillCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.setRefillCount = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional google.protobuf.Duration refill_frequency = 10;
 * @return {?proto.google.protobuf.Duration}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getRefillFrequency = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 10));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
*/
proto.heyrenee.v1.messages.Prescription.prototype.setRefillFrequency = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.clearRefillFrequency = function() {
  return this.setRefillFrequency(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.Prescription.prototype.hasRefillFrequency = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional PrescriptionStatus prescription_status = 11;
 * @return {!proto.heyrenee.v1.messages.PrescriptionStatus}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getPrescriptionStatus = function() {
  return /** @type {!proto.heyrenee.v1.messages.PrescriptionStatus} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {!proto.heyrenee.v1.messages.PrescriptionStatus} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.setPrescriptionStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 11, value);
};


/**
 * optional google.protobuf.Timestamp first_medication_regimen_start = 12;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getFirstMedicationRegimenStart = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 12));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
*/
proto.heyrenee.v1.messages.Prescription.prototype.setFirstMedicationRegimenStart = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.clearFirstMedicationRegimenStart = function() {
  return this.setFirstMedicationRegimenStart(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.Prescription.prototype.hasFirstMedicationRegimenStart = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional google.protobuf.Duration medication_regimen_duration = 13;
 * @return {?proto.google.protobuf.Duration}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getMedicationRegimenDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 13));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
*/
proto.heyrenee.v1.messages.Prescription.prototype.setMedicationRegimenDuration = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.clearMedicationRegimenDuration = function() {
  return this.setMedicationRegimenDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.Prescription.prototype.hasMedicationRegimenDuration = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional int64 medication_doses_per_regimen = 14;
 * @return {number}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getMedicationDosesPerRegimen = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.setMedicationDosesPerRegimen = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * repeated google.protobuf.Duration medication_dose_durations_from_regimen_start = 15;
 * @return {!Array<!proto.google.protobuf.Duration>}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getMedicationDoseDurationsFromRegimenStartList = function() {
  return /** @type{!Array<!proto.google.protobuf.Duration>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_duration_pb.Duration, 15));
};


/**
 * @param {!Array<!proto.google.protobuf.Duration>} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
*/
proto.heyrenee.v1.messages.Prescription.prototype.setMedicationDoseDurationsFromRegimenStartList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 15, value);
};


/**
 * @param {!proto.google.protobuf.Duration=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.Duration}
 */
proto.heyrenee.v1.messages.Prescription.prototype.addMedicationDoseDurationsFromRegimenStart = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 15, opt_value, proto.google.protobuf.Duration, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.clearMedicationDoseDurationsFromRegimenStartList = function() {
  return this.setMedicationDoseDurationsFromRegimenStartList([]);
};


/**
 * optional google.protobuf.Timestamp date_written = 16;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.heyrenee.v1.messages.Prescription.prototype.getDateWritten = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 16));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
*/
proto.heyrenee.v1.messages.Prescription.prototype.setDateWritten = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.heyrenee.v1.messages.Prescription} returns this
 */
proto.heyrenee.v1.messages.Prescription.prototype.clearDateWritten = function() {
  return this.setDateWritten(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.Prescription.prototype.hasDateWritten = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * @enum {number}
 */
proto.heyrenee.v1.messages.PrescriptionStatus = {
  PRESCRIPTION_STATUS_UNSPECIFIED: 0,
  PRESCRIPTION_ACTIVE: 1,
  PRESCRIPTION_INACTIVE: 2
};

goog.object.extend(exports, proto.heyrenee.v1.messages);
