// source: heyrenee/v1/messages/provider.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var heyrenee_v1_enums_specialty_pb = require('../../../heyrenee/v1/enums/specialty_pb.js');
goog.object.extend(proto, heyrenee_v1_enums_specialty_pb);
goog.exportSymbol('proto.heyrenee.v1.messages.Provider', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.heyrenee.v1.messages.Provider = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.heyrenee.v1.messages.Provider.repeatedFields_, null);
};
goog.inherits(proto.heyrenee.v1.messages.Provider, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.heyrenee.v1.messages.Provider.displayName = 'proto.heyrenee.v1.messages.Provider';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.heyrenee.v1.messages.Provider.repeatedFields_ = [4,15];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.heyrenee.v1.messages.Provider.prototype.toObject = function(opt_includeInstance) {
  return proto.heyrenee.v1.messages.Provider.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.heyrenee.v1.messages.Provider} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.messages.Provider.toObject = function(includeInstance, msg) {
  var f, obj = {
    providerId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    firstName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    lastName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    addressLinesList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    city: jspb.Message.getFieldWithDefault(msg, 5, ""),
    state: jspb.Message.getFieldWithDefault(msg, 6, ""),
    zip: jspb.Message.getFieldWithDefault(msg, 7, ""),
    phone: jspb.Message.getFieldWithDefault(msg, 8, ""),
    specialty: jspb.Message.getFieldWithDefault(msg, 9, 0),
    npi: jspb.Message.getFieldWithDefault(msg, 10, ""),
    facility: jspb.Message.getFieldWithDefault(msg, 11, ""),
    hours: jspb.Message.getFieldWithDefault(msg, 12, ""),
    ribbonId: jspb.Message.getFieldWithDefault(msg, 13, ""),
    secondaryFacility: jspb.Message.getFieldWithDefault(msg, 14, ""),
    secondaryAddressLinesList: (f = jspb.Message.getRepeatedField(msg, 15)) == null ? undefined : f,
    secondaryCity: jspb.Message.getFieldWithDefault(msg, 16, ""),
    secondaryState: jspb.Message.getFieldWithDefault(msg, 17, ""),
    secondaryZip: jspb.Message.getFieldWithDefault(msg, 18, ""),
    secondaryPhone: jspb.Message.getFieldWithDefault(msg, 19, ""),
    secondarySpecialty: jspb.Message.getFieldWithDefault(msg, 20, 0),
    secondaryHours: jspb.Message.getFieldWithDefault(msg, 21, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.heyrenee.v1.messages.Provider}
 */
proto.heyrenee.v1.messages.Provider.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.heyrenee.v1.messages.Provider;
  return proto.heyrenee.v1.messages.Provider.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.heyrenee.v1.messages.Provider} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.heyrenee.v1.messages.Provider}
 */
proto.heyrenee.v1.messages.Provider.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProviderId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFirstName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addAddressLines(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCity(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setState(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setZip(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhone(value);
      break;
    case 9:
      var value = /** @type {!proto.heyrenee.v1.enums.Specialty} */ (reader.readEnum());
      msg.setSpecialty(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setNpi(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setFacility(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setHours(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setRibbonId(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecondaryFacility(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.addSecondaryAddressLines(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecondaryCity(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecondaryState(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecondaryZip(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecondaryPhone(value);
      break;
    case 20:
      var value = /** @type {!proto.heyrenee.v1.enums.Specialty} */ (reader.readEnum());
      msg.setSecondarySpecialty(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setSecondaryHours(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.heyrenee.v1.messages.Provider.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.heyrenee.v1.messages.Provider.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.heyrenee.v1.messages.Provider} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.messages.Provider.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProviderId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFirstName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLastName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAddressLinesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getCity();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getState();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getZip();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getPhone();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getSpecialty();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
  f = message.getNpi();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getFacility();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getHours();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getRibbonId();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getSecondaryFacility();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getSecondaryAddressLinesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      15,
      f
    );
  }
  f = message.getSecondaryCity();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getSecondaryState();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
  f = message.getSecondaryZip();
  if (f.length > 0) {
    writer.writeString(
      18,
      f
    );
  }
  f = message.getSecondaryPhone();
  if (f.length > 0) {
    writer.writeString(
      19,
      f
    );
  }
  f = message.getSecondarySpecialty();
  if (f !== 0.0) {
    writer.writeEnum(
      20,
      f
    );
  }
  f = message.getSecondaryHours();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
};


/**
 * optional string provider_id = 1;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getProviderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setProviderId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string first_name = 2;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getFirstName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setFirstName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string last_name = 3;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getLastName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setLastName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated string address_lines = 4;
 * @return {!Array<string>}
 */
proto.heyrenee.v1.messages.Provider.prototype.getAddressLinesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setAddressLinesList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.addAddressLines = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.clearAddressLinesList = function() {
  return this.setAddressLinesList([]);
};


/**
 * optional string city = 5;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setCity = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string state = 6;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setState = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string zip = 7;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getZip = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setZip = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string phone = 8;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getPhone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setPhone = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional heyrenee.v1.enums.Specialty specialty = 9;
 * @return {!proto.heyrenee.v1.enums.Specialty}
 */
proto.heyrenee.v1.messages.Provider.prototype.getSpecialty = function() {
  return /** @type {!proto.heyrenee.v1.enums.Specialty} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.heyrenee.v1.enums.Specialty} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setSpecialty = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * optional string npi = 10;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getNpi = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setNpi = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string facility = 11;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getFacility = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setFacility = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string hours = 12;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getHours = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setHours = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string ribbon_id = 13;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getRibbonId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setRibbonId = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string secondary_facility = 14;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getSecondaryFacility = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setSecondaryFacility = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * repeated string secondary_address_lines = 15;
 * @return {!Array<string>}
 */
proto.heyrenee.v1.messages.Provider.prototype.getSecondaryAddressLinesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 15));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setSecondaryAddressLinesList = function(value) {
  return jspb.Message.setField(this, 15, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.addSecondaryAddressLines = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 15, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.clearSecondaryAddressLinesList = function() {
  return this.setSecondaryAddressLinesList([]);
};


/**
 * optional string secondary_city = 16;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getSecondaryCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setSecondaryCity = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * optional string secondary_state = 17;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getSecondaryState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setSecondaryState = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};


/**
 * optional string secondary_zip = 18;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getSecondaryZip = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 18, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setSecondaryZip = function(value) {
  return jspb.Message.setProto3StringField(this, 18, value);
};


/**
 * optional string secondary_phone = 19;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getSecondaryPhone = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 19, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setSecondaryPhone = function(value) {
  return jspb.Message.setProto3StringField(this, 19, value);
};


/**
 * optional heyrenee.v1.enums.Specialty secondary_specialty = 20;
 * @return {!proto.heyrenee.v1.enums.Specialty}
 */
proto.heyrenee.v1.messages.Provider.prototype.getSecondarySpecialty = function() {
  return /** @type {!proto.heyrenee.v1.enums.Specialty} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {!proto.heyrenee.v1.enums.Specialty} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setSecondarySpecialty = function(value) {
  return jspb.Message.setProto3EnumField(this, 20, value);
};


/**
 * optional string secondary_hours = 21;
 * @return {string}
 */
proto.heyrenee.v1.messages.Provider.prototype.getSecondaryHours = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.Provider} returns this
 */
proto.heyrenee.v1.messages.Provider.prototype.setSecondaryHours = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


goog.object.extend(exports, proto.heyrenee.v1.messages);
