// source: heyrenee/v1/messages/rpm_schedule.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var heyrenee_v1_messages_provider_pb = require('../../../heyrenee/v1/messages/provider_pb.js');
goog.object.extend(proto, heyrenee_v1_messages_provider_pb);
goog.exportSymbol('proto.heyrenee.v1.messages.RpmSchedule', null, global);
goog.exportSymbol('proto.heyrenee.v1.messages.RpmSchedule.ProviderCase', null, global);
goog.exportSymbol('proto.heyrenee.v1.messages.RpmScheduleStatus', null, global);
goog.exportSymbol('proto.heyrenee.v1.messages.RpmScheduleType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.heyrenee.v1.messages.RpmSchedule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.heyrenee.v1.messages.RpmSchedule.repeatedFields_, proto.heyrenee.v1.messages.RpmSchedule.oneofGroups_);
};
goog.inherits(proto.heyrenee.v1.messages.RpmSchedule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.heyrenee.v1.messages.RpmSchedule.displayName = 'proto.heyrenee.v1.messages.RpmSchedule';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.heyrenee.v1.messages.RpmSchedule.repeatedFields_ = [7];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.heyrenee.v1.messages.RpmSchedule.oneofGroups_ = [[8,9]];

/**
 * @enum {number}
 */
proto.heyrenee.v1.messages.RpmSchedule.ProviderCase = {
  PROVIDER_NOT_SET: 0,
  PROVIDER_ID: 8,
  PROVIDER_MESSAGE: 9
};

/**
 * @return {proto.heyrenee.v1.messages.RpmSchedule.ProviderCase}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.getProviderCase = function() {
  return /** @type {proto.heyrenee.v1.messages.RpmSchedule.ProviderCase} */(jspb.Message.computeOneofCase(this, proto.heyrenee.v1.messages.RpmSchedule.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.toObject = function(opt_includeInstance) {
  return proto.heyrenee.v1.messages.RpmSchedule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.heyrenee.v1.messages.RpmSchedule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.messages.RpmSchedule.toObject = function(includeInstance, msg) {
  var f, obj = {
    patientId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    rpmScheduleId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    rpmScheduleType: jspb.Message.getFieldWithDefault(msg, 3, 0),
    firstMeasurementRegimenStart: (f = msg.getFirstMeasurementRegimenStart()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    measurementRegimenDuration: (f = msg.getMeasurementRegimenDuration()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    measurementsPerRegimen: jspb.Message.getFieldWithDefault(msg, 6, 0),
    measurementDurationsFromRegimenStartList: jspb.Message.toObjectList(msg.getMeasurementDurationsFromRegimenStartList(),
    google_protobuf_duration_pb.Duration.toObject, includeInstance),
    providerId: jspb.Message.getFieldWithDefault(msg, 8, ""),
    providerMessage: (f = msg.getProviderMessage()) && heyrenee_v1_messages_provider_pb.Provider.toObject(includeInstance, f),
    rpmScheduleStatus: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.heyrenee.v1.messages.RpmSchedule}
 */
proto.heyrenee.v1.messages.RpmSchedule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.heyrenee.v1.messages.RpmSchedule;
  return proto.heyrenee.v1.messages.RpmSchedule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.heyrenee.v1.messages.RpmSchedule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.heyrenee.v1.messages.RpmSchedule}
 */
proto.heyrenee.v1.messages.RpmSchedule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPatientId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRpmScheduleId(value);
      break;
    case 3:
      var value = /** @type {!proto.heyrenee.v1.messages.RpmScheduleType} */ (reader.readEnum());
      msg.setRpmScheduleType(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setFirstMeasurementRegimenStart(value);
      break;
    case 5:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setMeasurementRegimenDuration(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMeasurementsPerRegimen(value);
      break;
    case 7:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.addMeasurementDurationsFromRegimenStart(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setProviderId(value);
      break;
    case 9:
      var value = new heyrenee_v1_messages_provider_pb.Provider;
      reader.readMessage(value,heyrenee_v1_messages_provider_pb.Provider.deserializeBinaryFromReader);
      msg.setProviderMessage(value);
      break;
    case 10:
      var value = /** @type {!proto.heyrenee.v1.messages.RpmScheduleStatus} */ (reader.readEnum());
      msg.setRpmScheduleStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.heyrenee.v1.messages.RpmSchedule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.heyrenee.v1.messages.RpmSchedule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heyrenee.v1.messages.RpmSchedule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPatientId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRpmScheduleId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRpmScheduleType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getFirstMeasurementRegimenStart();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getMeasurementRegimenDuration();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getMeasurementsPerRegimen();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getMeasurementDurationsFromRegimenStartList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getProviderMessage();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      heyrenee_v1_messages_provider_pb.Provider.serializeBinaryToWriter
    );
  }
  f = message.getRpmScheduleStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      10,
      f
    );
  }
};


/**
 * optional string patient_id = 1;
 * @return {string}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.getPatientId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.setPatientId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string rpm_schedule_id = 2;
 * @return {string}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.getRpmScheduleId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.setRpmScheduleId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional RpmScheduleType rpm_schedule_type = 3;
 * @return {!proto.heyrenee.v1.messages.RpmScheduleType}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.getRpmScheduleType = function() {
  return /** @type {!proto.heyrenee.v1.messages.RpmScheduleType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.heyrenee.v1.messages.RpmScheduleType} value
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.setRpmScheduleType = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp first_measurement_regimen_start = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.getFirstMeasurementRegimenStart = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
*/
proto.heyrenee.v1.messages.RpmSchedule.prototype.setFirstMeasurementRegimenStart = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.clearFirstMeasurementRegimenStart = function() {
  return this.setFirstMeasurementRegimenStart(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.hasFirstMeasurementRegimenStart = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Duration measurement_regimen_duration = 5;
 * @return {?proto.google.protobuf.Duration}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.getMeasurementRegimenDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 5));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
*/
proto.heyrenee.v1.messages.RpmSchedule.prototype.setMeasurementRegimenDuration = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.clearMeasurementRegimenDuration = function() {
  return this.setMeasurementRegimenDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.hasMeasurementRegimenDuration = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional int64 measurements_per_regimen = 6;
 * @return {number}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.getMeasurementsPerRegimen = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.setMeasurementsPerRegimen = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * repeated google.protobuf.Duration measurement_durations_from_regimen_start = 7;
 * @return {!Array<!proto.google.protobuf.Duration>}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.getMeasurementDurationsFromRegimenStartList = function() {
  return /** @type{!Array<!proto.google.protobuf.Duration>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_duration_pb.Duration, 7));
};


/**
 * @param {!Array<!proto.google.protobuf.Duration>} value
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
*/
proto.heyrenee.v1.messages.RpmSchedule.prototype.setMeasurementDurationsFromRegimenStartList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.google.protobuf.Duration=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.Duration}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.addMeasurementDurationsFromRegimenStart = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.google.protobuf.Duration, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.clearMeasurementDurationsFromRegimenStartList = function() {
  return this.setMeasurementDurationsFromRegimenStartList([]);
};


/**
 * optional string provider_id = 8;
 * @return {string}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.getProviderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.setProviderId = function(value) {
  return jspb.Message.setOneofField(this, 8, proto.heyrenee.v1.messages.RpmSchedule.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.clearProviderId = function() {
  return jspb.Message.setOneofField(this, 8, proto.heyrenee.v1.messages.RpmSchedule.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.hasProviderId = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional Provider provider_message = 9;
 * @return {?proto.heyrenee.v1.messages.Provider}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.getProviderMessage = function() {
  return /** @type{?proto.heyrenee.v1.messages.Provider} */ (
    jspb.Message.getWrapperField(this, heyrenee_v1_messages_provider_pb.Provider, 9));
};


/**
 * @param {?proto.heyrenee.v1.messages.Provider|undefined} value
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
*/
proto.heyrenee.v1.messages.RpmSchedule.prototype.setProviderMessage = function(value) {
  return jspb.Message.setOneofWrapperField(this, 9, proto.heyrenee.v1.messages.RpmSchedule.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.clearProviderMessage = function() {
  return this.setProviderMessage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.hasProviderMessage = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional RpmScheduleStatus rpm_schedule_status = 10;
 * @return {!proto.heyrenee.v1.messages.RpmScheduleStatus}
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.getRpmScheduleStatus = function() {
  return /** @type {!proto.heyrenee.v1.messages.RpmScheduleStatus} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {!proto.heyrenee.v1.messages.RpmScheduleStatus} value
 * @return {!proto.heyrenee.v1.messages.RpmSchedule} returns this
 */
proto.heyrenee.v1.messages.RpmSchedule.prototype.setRpmScheduleStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 10, value);
};


/**
 * @enum {number}
 */
proto.heyrenee.v1.messages.RpmScheduleType = {
  RPM_SCHEDULE_TYPE_UNSPECIFIED: 0,
  RPM_SCHEDULE_TYPE_HEART_RATE: 1,
  RPM_SCHEDULE_TYPE_BLOOD_PRESSURE: 2,
  RPM_SCHEDULE_TYPE_PULSE: 3,
  RPM_SCHEDULE_TYPE_SP_O2: 4,
  RPM_SCHEDULE_TYPE_WEIGHT: 5,
  RPM_SCHEDULE_TYPE_GLUCOSE: 6
};

/**
 * @enum {number}
 */
proto.heyrenee.v1.messages.RpmScheduleStatus = {
  RPM_SCHEDULE_STATUS_UNSPECIFIED: 0,
  RPM_SCHEDULE_ACTIVE: 1,
  RPM_SCHEDULE_INACTIVE: 2
};

goog.object.extend(exports, proto.heyrenee.v1.messages);
