// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: heyrenee/v1/messages/concierge.proto

package messages

import (
	_ "github.com/HeyReneeInc/proto/golang/heyrenee/v1/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConciergeStatus specifies the status of a Concierge.
type ConciergeStatus int32

const (
	// The status of the Concierge is unspecified.
	ConciergeStatus_CONCIERGE_STATUS_UNSPECIFIED ConciergeStatus = 0
	// The Concierge is currently active.
	ConciergeStatus_CONCIERGE_STATUS_ACTIVE ConciergeStatus = 1
	// The Concierge is currently inactive.
	ConciergeStatus_CONCIERGE_STATUS_INACTIVE ConciergeStatus = 2
)

// Enum value maps for ConciergeStatus.
var (
	ConciergeStatus_name = map[int32]string{
		0: "CONCIERGE_STATUS_UNSPECIFIED",
		1: "CONCIERGE_STATUS_ACTIVE",
		2: "CONCIERGE_STATUS_INACTIVE",
	}
	ConciergeStatus_value = map[string]int32{
		"CONCIERGE_STATUS_UNSPECIFIED": 0,
		"CONCIERGE_STATUS_ACTIVE":      1,
		"CONCIERGE_STATUS_INACTIVE":    2,
	}
)

func (x ConciergeStatus) Enum() *ConciergeStatus {
	p := new(ConciergeStatus)
	*p = x
	return p
}

func (x ConciergeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConciergeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_heyrenee_v1_messages_concierge_proto_enumTypes[0].Descriptor()
}

func (ConciergeStatus) Type() protoreflect.EnumType {
	return &file_heyrenee_v1_messages_concierge_proto_enumTypes[0]
}

func (x ConciergeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConciergeStatus.Descriptor instead.
func (ConciergeStatus) EnumDescriptor() ([]byte, []int) {
	return file_heyrenee_v1_messages_concierge_proto_rawDescGZIP(), []int{0}
}

// A Concierge represents a subuser that is responsible for coordinating the care of Patients they are a
// PatientConcierge for.
type Concierge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the Concierge. Required.
	ConciergeId string `protobuf:"bytes,1,opt,name=concierge_id,json=conciergeId,proto3" json:"concierge_id,omitempty"`
	// The legal first name of the Concierge. Required.
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// The legal last name of the Concierge. Required.
	LastName string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// The email address for contacting the Concierge. Required.
	Email string `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	// The status of the Concierge. Required.
	ConciergeStatus ConciergeStatus `protobuf:"varint,5,opt,name=concierge_status,json=conciergeStatus,proto3,enum=heyrenee.v1.messages.ConciergeStatus" json:"concierge_status,omitempty"`
}

func (x *Concierge) Reset() {
	*x = Concierge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_heyrenee_v1_messages_concierge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Concierge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Concierge) ProtoMessage() {}

func (x *Concierge) ProtoReflect() protoreflect.Message {
	mi := &file_heyrenee_v1_messages_concierge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Concierge.ProtoReflect.Descriptor instead.
func (*Concierge) Descriptor() ([]byte, []int) {
	return file_heyrenee_v1_messages_concierge_proto_rawDescGZIP(), []int{0}
}

func (x *Concierge) GetConciergeId() string {
	if x != nil {
		return x.ConciergeId
	}
	return ""
}

func (x *Concierge) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Concierge) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Concierge) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Concierge) GetConciergeStatus() ConciergeStatus {
	if x != nil {
		return x.ConciergeStatus
	}
	return ConciergeStatus_CONCIERGE_STATUS_UNSPECIFIED
}

var File_heyrenee_v1_messages_concierge_proto protoreflect.FileDescriptor

var file_heyrenee_v1_messages_concierge_proto_rawDesc = []byte{
	0x0a, 0x24, 0x68, 0x65, 0x79, 0x72, 0x65, 0x6e, 0x65, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x65, 0x72, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x68, 0x65, 0x79, 0x72, 0x65, 0x6e, 0x65, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x1e, 0x68, 0x65,
	0x79, 0x72, 0x65, 0x6e, 0x65, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd8, 0x01, 0x0a,
	0x09, 0x43, 0x6f, 0x6e, 0x63, 0x69, 0x65, 0x72, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x0c, 0x63, 0x6f,
	0x6e, 0x63, 0x69, 0x65, 0x72, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x04, 0x80, 0xb5, 0x18, 0x03, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x65, 0x72, 0x67,
	0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x50, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x65, 0x72,
	0x67, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x25, 0x2e, 0x68, 0x65, 0x79, 0x72, 0x65, 0x6e, 0x65, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x63, 0x69, 0x65, 0x72, 0x67, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x63, 0x69, 0x65, 0x72, 0x67,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x6f, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x63, 0x69,
	0x65, 0x72, 0x67, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x20, 0x0a, 0x1c, 0x43, 0x4f,
	0x4e, 0x43, 0x49, 0x45, 0x52, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1b, 0x0a, 0x17,
	0x43, 0x4f, 0x4e, 0x43, 0x49, 0x45, 0x52, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x4f, 0x4e,
	0x43, 0x49, 0x45, 0x52, 0x47, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x49, 0x4e,
	0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x02, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x48, 0x65, 0x79, 0x52, 0x65, 0x6e, 0x65, 0x65, 0x49,
	0x6e, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f,
	0x68, 0x65, 0x79, 0x72, 0x65, 0x6e, 0x65, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_heyrenee_v1_messages_concierge_proto_rawDescOnce sync.Once
	file_heyrenee_v1_messages_concierge_proto_rawDescData = file_heyrenee_v1_messages_concierge_proto_rawDesc
)

func file_heyrenee_v1_messages_concierge_proto_rawDescGZIP() []byte {
	file_heyrenee_v1_messages_concierge_proto_rawDescOnce.Do(func() {
		file_heyrenee_v1_messages_concierge_proto_rawDescData = protoimpl.X.CompressGZIP(file_heyrenee_v1_messages_concierge_proto_rawDescData)
	})
	return file_heyrenee_v1_messages_concierge_proto_rawDescData
}

var file_heyrenee_v1_messages_concierge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_heyrenee_v1_messages_concierge_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_heyrenee_v1_messages_concierge_proto_goTypes = []interface{}{
	(ConciergeStatus)(0), // 0: heyrenee.v1.messages.ConciergeStatus
	(*Concierge)(nil),    // 1: heyrenee.v1.messages.Concierge
}
var file_heyrenee_v1_messages_concierge_proto_depIdxs = []int32{
	0, // 0: heyrenee.v1.messages.Concierge.concierge_status:type_name -> heyrenee.v1.messages.ConciergeStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_heyrenee_v1_messages_concierge_proto_init() }
func file_heyrenee_v1_messages_concierge_proto_init() {
	if File_heyrenee_v1_messages_concierge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_heyrenee_v1_messages_concierge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Concierge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_heyrenee_v1_messages_concierge_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_heyrenee_v1_messages_concierge_proto_goTypes,
		DependencyIndexes: file_heyrenee_v1_messages_concierge_proto_depIdxs,
		EnumInfos:         file_heyrenee_v1_messages_concierge_proto_enumTypes,
		MessageInfos:      file_heyrenee_v1_messages_concierge_proto_msgTypes,
	}.Build()
	File_heyrenee_v1_messages_concierge_proto = out.File
	file_heyrenee_v1_messages_concierge_proto_rawDesc = nil
	file_heyrenee_v1_messages_concierge_proto_goTypes = nil
	file_heyrenee_v1_messages_concierge_proto_depIdxs = nil
}
